export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_FAILED = 'NEWS_DETAILS_FAILED';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';

export const NEWS_TECH_REQUEST = 'NEWS_TECH_REQUEST';
export const NEWS_TECH_FAILED = 'NEWS_TECH_FAILED';
export const NEWS_TECH_SUCCESS = 'NEWS_TECH_SUCCESS';

export const NEWS_BUSINESS_REQUEST = 'NEWS_BUSINESS_REQUEST';
export const NEWS_BUSINESS_FAILED = 'NEWS_BUSINESS_FAILED';
export const NEWS_BUSINESS_SUCCESS = 'NEWS_BUSINESS_SUCCESS';

export const NEWS_SCIENCE_REQUEST = 'NEWS_SCIENCE_REQUEST';
export const NEWS_SCIENCE_FAILED = 'NEWS_SCIENCE_FAILED';
export const NEWS_SCIENCE_SUCCESS = 'NEWS_SCIENCE_SUCCESS';

export const NEWS_HEALTH_REQUEST = 'NEWS_HEALTH_REQUEST';
export const NEWS_HEALTH_FAILED = 'NEWS_HEALTH_FAILED';
export const NEWS_HEALTH_SUCCESS = 'NEWS_HEALTH_SUCCESS';

export const NEWS_ENTERTAINMENT_REQUEST = 'NEWS_ENTERTAINMENT_REQUEST';
export const NEWS_ENTERTAINMENT_FAILED = 'NEWS_ENTERTAINMENT_FAILED';
export const NEWS_ENTERTAINMENT_SUCCESS = 'NEWS_ENTERTAINMENT_SUCCESS';

export const NEWS_SPORTS_REQUEST = 'NEWS_SPORTS_REQUEST';
export const NEWS_SPORTS_FAILED = 'NEWS_SPORTS_FAILED';
export const NEWS_SPORTS_SUCCESS = 'NEWS_SPORTS_SUCCESS';

export const NEWS_SEARCH_REQUEST = 'NEWS_SEARCH_REQUEST';
export const NEWS_SEARCH_FAILED = 'NEWS_SEARCH_FAILED';
export const NEWS_SEARCH_SUCCESS = 'NEWS_SEARCH_SUCCESS';

export const NEWS_GAMING_REQUEST = 'NEWS_GAMING_REQUEST';
export const NEWS_GAMING_FAILED = 'NEWS_GAMING_FAILED';
export const NEWS_GAMING_SUCCESS = 'NEWS_GAMING_SUCCESS';
